<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use HasFactory,SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'title',
        'slug',

    ];



    public function delete()
    {
        $this->posts()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function posts()
    {
        return $this->belongsToMany(\App\Models\Post::class)->withTimestamps();
    }

}
